//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AmbObject.rc
//
#define IDS_SIZE                        1
#define IDS_NAMELIST                    2
#define IDS_ENTRY1                      3
#define IDS_ENTRY2                      4
#define IDS_ENTRY3                      5
#define IDR_AMBIENT                     101

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
