//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by jwe.rc
//
#define IDR_MANIFEST                    1
#define IDD_ABOUTBOX                    10
#define IDP_OLE_INIT_FAILED             14
#define IDS_STRING_GLOBALMATERIALS      15
#define IDS_ARCH_STARTANGLE             15
#define IDS_STRING_MASTER               16
#define IDS_ARCH_ENDANGLE               17
#define IDC_TEXT_BUILDINFO              18
#define IDS_ARCH_THICKNESS              18
#define IDS_ARCH_WIDTH                  19
#define IDS_ARCH_INNERRADIUS            20
#define IDS_ARCH_HOLLOWWALLSIZE         21
#define IDC_TEXT_JETLINK                22
#define IDS_ARCH_NUMCROSSSECTIONS       22
#define ID_INDICATOR_PERF               23
#define ID_INDICATOR_POS                24
#define ID_INDICATOR_SIZE               25
#define IDD_OBJECTBAR                   26
#define IDC_TEXT_JETLINK1               30
#define IDC_ABOUT_STATIC1               34
#define IDC_ABOUT_STATIC                38
#define IDC_ABOUT_STATIC2               42
#define IDC_TEXT_JETLINK2               46
#define IDC_TEXT_JETLINK3               50
#define IDC_ABOUT_STATIC3               54
#define IDR_MAINFRAME                   58
#define IDR_GWFTYPE                     62
#define IDR_PREFABDESC                  63
#define IDR_MATERIALDESC                64
#define IDM_VIEW_TEXTURED               75
#define IDM_VIEW_WIREFRAME              76
#define IDM_VIEW_RESERVED1              77
#define IDM_VIEW_RESERVED2              78
#define IDM_VIEW_TOP                    82
#define IDM_VIEW_FRONT                  86
#define IDM_VIEW_SIDE                   90
#define IDM_VIEW_RESERVED3              94
#define IDM_VIEW_RESERVED4              98
#define IDD_DRIVERDIALOG                102
#define IDS_TAB_GROUPS                  106
#define IDS_TAB_RENDER                  110
#define IDC_DRIVERLIST                  114
#define IDS_TAB_TEMPLATES               118
#define IDD_COMMANDPANEL                122
#define IDS_TAB_TEXTURES                126
#define CPNL_TC_TABS                    130
#define IDS_TAB_ENTITIES                134
#define IDS_TAB_LISTS                   138
#define IDD_GROUPS                      142
#define IDS_TAB_MODELS                  146
#define IDD_TEMPLATES                   150
#define IDS_TAB_SOUNDS                  154
#define IDS_TAB_GROUP                   158
#define IDD_TEXTURE                     162
#define IDS_TAB_ACTORS                  166
#define IDI_ARCH                        170
#define IDS_TAB_PROPERTIES              174
#define IDI_CONE                        178
#define IDS_TAB_RESERVED2               182
#define IDI_CUBE                        186
#define IDS_TAB_RESERVED3               190
#define IDI_CYLINDER                    194
#define IDS_TAB_RESERVED4               198
#define IDI_SPHERE                      202
#define IDS_TOOLBAR_GENERAL             206
#define IDI_STAIRS                      210
#define IDS_TOOLBAR_MODE                214
#define IDD_ENTITIES                    218
#define IDS_TOOLBAR_GROUP               222
#define IDS_TOOLBAR_OBJECT              226
#define IDD_MODELS                      230
#define IDS_TOOLBAR_ALIGNMENT           234
#define IDR_IMAGELIST1                  238
#define IDR_GROUPS                      238
#define IDS_TOOLBAR_ORTHO               242
#define IDS_REGISTRYKEY                 246
#define IDS_BRUSH_SOLID                 250
#define IDS_BRUSH_CLIP                  254
#define IDR_MODE                        258
#define IDS_BRUSH_EMPTY                 262
#define IDS_BRUSH_WINDOW                266
#define IDR_OBJECTS                     270
#define IDD_FACE                        274
#define IDS_BRUSH_CUT                   278
#define IDD_EMPTY                       282
#define IDS_BRUSH_RESERVED1             286
#define IDD_BRUSH                       290
#define IDS_BRUSH_RESERVED2             294
#define IDS_BRUSH_RESERVED3             298
#define IDS_BRUSH_RESERVED4             302
#define IDD_GROUPBAR                    306
#define IDS_FRONT                       310
#define IDS_SIDE                        314
#define IDB_SHOWALL                     318
#define IDS_TOP                         322
#define IDB_SHOWVISIBLEGROUPS           326
#define IDS_LOFTER                      330
#define IDB_SHOWCURRENTGROUP            334
#define IDS_PANE_RESERVED1              338
#define IDB_ADDTOCURRENTGROUP           342
#define IDS_PANE_RESERVED2              346
#define IDB_REMOVEFROMCURRENT           350
#define IDS_PANE_RESERVED3              354
#define IDS_DEFAULTGROUPNAME            358
#define IDB_HANDLECORNER                362
#define IDB_HANDLEEDGE                  366
#define IDS_TEMP_PREFIX                 370
#define IDB_ROTATEHANDLETL              374
#define IDS_BAK_EXT                     378
#define IDB_ROTATEHANDLETR              382
#define IDS_CANTOPENFILE                386
#define IDB_ROTATEHANDLEBL              390
#define IDS_ERRORWRITING                394
#define IDB_ROTATEHANDLEBR              398
#define IDS_ERRORCLOSING                402
#define IDS_ERRORREADINGFILE            406
#define IDB_SHEARHANDLELR               410
#define IDS_TOOLBAR_POSANDSIZE          414
#define IDB_SHEARHANDLETB               418
#define IDS_UNDO                        422
#define IDC_MOVESELECT                  426
#define IDS_REDO                        430
#define IDS_UNDOACCEL                   434
#define IDC_ROTATIONCENTER              438
#define IDS_REDOACCEL                   442
#define IDS_BRUSH_BOX                   446
#define IDC_SHEARLR                     450
#define IDS_BRUSH_CYLINDER              454
#define IDC_SHEARTB                     458
#define IDS_BRUSH_ARCH                  462
#define IDC_ROTATE                      466
#define IDS_BRUSH_CONE                  470
#define IDC_DRAGCOPY                    474
#define IDS_BRUSH_STAIRCASE             478
#define IDC_DRAGMOVE                    482
#define IDS_BRUSH_PREMADE               486
#define IDD_GRIDSETTINGS                490
#define IDS_BRUSH_LOFTED                494
#define IDS_LIGHT                       498
#define IDI_TILE128                     502
#define IDI_TILE64                      506
#define IDS_ENTITYTYPE_INT              510
#define IDI_TILE32                      514
#define IDS_ENTITYTYPE_STRING           518
#define IDI_LIGHT                       522
#define IDS_ENTITYTYPE_FLOAT            526
#define IDD_TEMPLATELIGHT               530
#define IDS_ENTITYTYPE_VEC3D            534
#define IDB_VERTEX                      538
#define IDS_ENTITYTYPE_COLOR            542
#define IDB_SELVERTEX                   546
#define IDS_ENTITYTYPE_BOOL             550
#define IDD_DEFINEENTITIES              554
#define IDS_ENTITYTYPE_ENUM             558
#define IDS_ENTITYTYPE_VOIDP            562
#define IDD_NEWMODEL                    566
#define IDS_ENTITYTYPE_LIST             570
#define IDI_ENTITY                      574
#define IDS_ENTITYTYPE_SYMBOL           578
#define IDD_TEMPLATEENTITY              582
#define IDS_ENTITYTYPE_MODEL            586
#define IDI_TERRAIN                     590
#define IDD_TEMPLATETERRAIN             594
#define IDS_ENTITYTYPE_PORTAL           598
#define IDB_TERRAIN                     602
#define IDI_SHEET                       606
#define IDS_ENTITYTYPE_R5               610
#define IDD_LIGHT                       614
#define IDS_ENTITYTYPE_R6               618
#define IDD_LISTS                       622
#define IDS_ENTITYTYPE_R7               626
#define IDD_TEMPLATESPHERE              630
#define IDS_ENTITYTYPE_R8               634
#define IDD_TEMPLATECYLND               638
#define IDS_TRUE                        642
#define IDD_DIALOG1                     646
#define IDS_FALSE                       650
#define IDD_RENDER                      654
#define IDS_MUSTSELBRUSH                658
#define IDD_TEMPLATESHEET               662
#define IDS_MUSTSUPPLYNAME              666
#define IDD_REBUILD                     670
#define IDS_MUSTSUPPLYDEFAULT           674
#define IDS_OUTOFMEMORY                 678
#define IDD_GLOBALMATERIALS             682
#define IDS_NEWMODEL                    686
#define IDD_MATERIALLIST                690
#define IDS_NEWENTITY                   694
#define IDD_MATERIALBAR                 698
#define IDS_FAILEDTOCREATE              702
#define IDD_PROPERTIEBAR                706
#define IDS_CONFIRMDELETEENTITIES       710
#define IDD_PROPERTIEDLG                714
#define IDS_TERRAIN                     718
#define IDS_ADDBRUSH                    722
#define IDD_MATERIAL                    726
#define IDS_ADD                         730
#define IDS_TOOLBAR_EDIT                734
#define IDS_ADDLIGHT                    738
#define IDS_TABENTER                    742
#define IDS_DEFAULTLIGHTTEMPLATENAME    746
#define IDS_ADDTERRAIN                  750
#define IDS_MULTSELNAME                 754
#define IDC_CUBE                        758
#define IDS_NOSELECTION                 762
#define IDC_CYLINDER                    766
#define IDS_DEFAULTSPHERETEMPLATENAME   770
#define IDC_SPHERE                      774
#define IDS_NEWGROUP                    778
#define IDC_LIGHT                       782
#define IDS_DEFAULTSHEETTEMPLATENAME    786
#define IDC_SHEET                       790
#define IDS_NAME_FIELD                  794
#define IDD_DIALOG2                     798
#define IDS_POSITION_FIELD              802
#define IDD_DISCLAIMER                  810
#define IDS_POSITIONX_FIELD             814
#define IDR_BUILD                       818
#define IDS_POSITIONY_FIELD             822
#define IDS_POSITIONZ_FIELD             826
#define IDC_CAMERA                      830
#define IDS_FLOCKING_FIELD              834
#define IDI_CAMERA                      838
#define IDS_SOLID_FIELD                 842
#define IDI_SPECIALEFFECT               846
#define IDS_EMPTY_FIELD                 850
#define IDC_SPECIALEFFECT               854
#define IDS_AIR_FIELD                   858
#define IDR_TEXT1                       862
#define IDS_COLOR_FIELD                 866
#define IDR_TEXT2                       870
#define IDS_BRIGHTNESS_FIELD            874
#define IDS_RADIUS_FIELD                878
#define IDR_VIEW                        882
#define IDS_RED_FIELD                   886
#define IDR_3DVIEW                      890
#define IDS_GREEN_FIELD                 894
#define IDD_TIMELINE                    898
#define IDS_BLUE_FIELD                  902
#define IDS_FACE_FIELD                  906
#define IDD_ERROR                       910
#define IDS_GOURAND_FIELD               914
#define IDC_CURSOR_PLUS                 918
#define IDS_FLAT_FIELD                  922
#define IDD_MOUSEPROP                   926
#define IDS_TRANSPARENT_FIELD           930
#define IDS_MIRROR_FIELD                934
#define IDD_PREFERENCES                 938
#define IDS_FULLBRIGHT_FIELD            942
#define IDB_PREFS_PATHS                 946
#define IDS_VIS_PORTAL_FIELD            950
#define IDB_PREFS_COLORS                954
#define IDS_ALPHA_FIELD                 958
#define IDD_PRESS_A_KEY                 962
#define IDB_PREFS_GRID                  966
#define IDS_ROTATE_FIELD                970
#define IDB_PREFS_KEYS                  974
#define IDS_SHIFTU_FIELD                978
#define IDB_PREFS_SCRIPT                982
#define IDS_SHIFTV_FIELD                986
#define IDB_PREFS_MOUSE                 990
#define IDS_DRAWSCALEU_FIELD            994
#define IDB_PREFS_JET                   998
#define IDI_PREFS_VIEW                  1002
#define IDS_DRAWSCALEV_FIELD            1006
#define IDB_PREFS_VIEW                  1010
#define IDS_LMAPSCALEU_FIELD            1014
#define IDS_LMAPSCALEV_FIELD            1018
#define IDR_POSSIZE                     1022
#define IDS_SHIFT_FIELD                 1026
#define IDS_DRAWSCALE_FIELD             1030
#define IDR_EDIT                        1034
#define IDS_LIGHTMAP_FIELD              1038
#define IDB_PREFS_GLOBAL                1042
#define IDS_BOXXRATIO_FIELD             1046
#define IDR_TOOLBARS                    1050
#define IDS_BOXZRATIO_FIELD             1054
#define IDS_SPHERE_HBANDS_FIELD         1058
#define IDS_SPHERE_VBANDS_FIELD         1062
#define IDI_DIALOG_FULLSCREEN           1066
#define IDS_CYLDXRATIO_FIELD            1070
#define IDI_DIALOG_TREE                 1074
#define IDS_CYLDZRATIO_FIELD            1078
#define IDS_CYLD_STRIPE_FIELD           1082
#define IDB_JEDIT_SPLASH                1086
#define IDS_TEMPLATE_FIELD              1090
#define IDI_ARR_NW                      1094
#define IDS_BRUSH_SHEET                 1098
#define IDI_ARR_SW                      1102
#define IDS_BRUSH_SPHERE                1106
#define IDI_ARR_SO                      1110
#define IDS_PICKER_FIELD                1114
#define IDI_ARR_NO                      1118
#define IDS_CAMERA                      1122
#define IDI_GLOBE                       1126
#define IDS_SPECIALEFFECT               1130
#define IDD_PROPERTIES                  1134
#define IDS_ABOUT                       1138
#define IDI_PREFS_GLOBAL                1142
#define IDD_EXTFILEDIALOG               1146
#define IDS_BRUSH                       1150
#define IDI_PREFS_GRID                  1154
#define IDS_USEROBJ                     1158
#define IDI_PREFS_MOUSE                 1162
#define IDS_RENDER_LINES                1166
#define IDI_PREFS_KEYS                  1170
#define IDS_RENDER_FLAT                 1174
#define IDI_PREFS_PATHS                 1178
#define IDS_RENDER_BSPSPLITS            1182
#define IDI_DOWN                        1186
#define IDS_RENDER_TEXTURED             1190
#define IDC_HAND_JET                    1194
#define IDS_RENDER_TEXT_LIT             1198
#define IDC_HAND_OPEN                   1202
#define IDS_VIS_PORTAL_COMBO            1206
#define IDS_RENDER_PORTAL_FIELD         1210
#define IDS_PORTAL_ONLY_FIELD           1214
#define IDS_UPDATE                      1218
#define IDS_UPDATE_MANUEL               1222
#define IDS_UPDATE_CHANGE               1226
#define IDS_UPDATE_REALTIME             1230
#define IDS_MAINTAIN_LIGHTING           1234
#define IDI_PREFS_JET                   1238
#define IDI_PROPERTIES_SUMMARY          1242
#define IDI_PROPERTIES_CONTENTS         1246
#define IDI_PROPERTIES_CUSTOM           1250
#define IDI_UP                          1254
#define IDI_RIGHT                       1258
#define IDI_LEFT                        1262
#define IDI_INFO                        1266
#define IDI_PREFS_EDIT                  1270
#define IDI_ZOOMOUT                     1274
#define IDI_ZOOMIN                      1278
#define IDI_RESET                       1282
#define IDI_PLAY                        1286
#define IDI_CUT                         1290
#define IDI_PLAYING                     1294
#define IDI_LOCK                        1298
#define IDI_UNLOCK                      1302
#define IDI_TIMECOLOR                   1306
#define IDI_TIME                        1310
#define GROUP_ADDTOCURRENT              1314
#define GRUP_BN_ADDTOCURRENT            1318
#define GROUP_REMOVESELECTIONS          1322
#define GRUP_BN_REMOVESELECTIONS        1326
#define GROUP_TREE                      1330
#define GRUP_TC                         1334
#define GROUP_CREATE                    1338
#define GROUP_LOCK                      1342
#define TEMPLATE_ADDCUBE                1346
#define TEMPLATE_ADDSPHEROID            1350
#define TEMPLATE_ADDCYLINDER            1354
#define TEMPLATE_ADDSTAIRCASE           1358
#define TEMPLATE_CB_PREMADE             1362
#define TMPL_CB_PREMADE                 1366
#define TEMPLATE_BN_ADD                 1370
#define TMPL_BN_ADDPREMADE              1374
#define TMPL_CB_LOFTER                  1378
#define TXTR_PC_IMAGES                  1382
#define TXTR_SB                         1386
#define TXTR_ST_INFO                    1390
#define TXTR_CB_CATAGORY                1394
#define TMPL_CB_LOFTERSPLINE            1398
#define ENTY_CB_TYPE                    1402
#define TXTR_CB_NAME                    1406
#define ENTY_BN_PLACE                   1410
#define ENTY_TV_LIST                    1414
#define ENTY_BN_COLOR                   1418
#define ENTY_BN_ORTHOCOLOR              1422
#define MODL_CB_CURRENT                 1426
#define MODL_BN_ADD                     1430
#define MODL_BN_DELETE                  1434
#define GRUP_CB_CURRENT                 1438
#define MODL_BN_EDIT                    1442
#define IDS_UNDO_MOVE                   1446
#define GRUP_BN_SELECTITEMS             1450
#define IDS_UNDO_ROTATE                 1454
#define GRUP_BN_UNSELECTITEMS           1458
#define IDS_UNDO_RESIZE                 1462
#define GRUP_BN_COLOR                   1466
#define IDS_UNDO_DELETE                 1470
#define ENTY_LB_PROPERTIES              1474
#define IDS_UNDO_APPLY                  1478
#define ENTY_BN_SHOWALL                 1482
#define ENTY_BN_HIDEALL                 1486
#define IDS_UNDO_NONE                   1490
#define ENTY_BN_COLLAPSE                1494
#define IDS_UNO_CREATE                  1498
#define GRUP_BN_SHOWREVERT              1502
#define TMPL_RB_REVOLVE                 1506
#define IDS_UNDO_SHEAR                  1510
#define TMPL_RB_EXTRUDE                 1514
#define TMPL_RB_EXTRUDETOPOINT          1518
#define TMPL_ED_CAP                     1522
#define TMPL_ED_DEPTH                   1526
#define FACE_CK_PORTAL                  1530
#define TMPL_ED_FACES                   1534
#define FACE_CK_SKY                     1538
#define FACE_CK_INVISIBLE               1542
#define TMPL_ED_FACESIN360              1546
#define FACE_CK_TEXTURELOCK             1550
#define FACE_CK_FULLBRIGHT              1554
#define FACE_CK_GOURAUD                 1558
#define FACE_CK_FLAT                    1562
#define FACE_CK_LIGHT                   1566
#define FACE_ED_LIGHT                   1570
#define FACE_ED_TEXTUREX                1574
#define FACE_SP_TEXTUREX                1578
#define FACE_ED_TEXTUREY                1582
#define FACE_SP_TEXTUREY                1586
#define FACE_ED_DRAWSCALEX              1590
#define FACE_SP_DRAWSCALEX              1594
#define FACE_ED_DRAWSCALEY              1598
#define FACE_SP_DRAWSCALEY              1602
#define FACE_ED_LIGHTMAPX               1606
#define FACE_ED_LIGHTMAPY               1610
#define FACE_SP_LIGHTMAPX               1614
#define FACE_SP_LIGHTMAPY               1618
#define FACE_ED_ANGLE                   1622
#define FACE_SP_ANGLE                   1626
#define FACE_ED_MIPMAPBIAS              1630
#define IDC_EDIT4                       1634
#define FACE_CK_TRANSPARENT             1638
#define FACE_ED_TRANSPARENT             1642
#define FACE_BN_FLIPH                   1646
#define FACE_BN_FLIPV                   1650
#define FACE_BN_DEFAULTS                1654
#define FACE_ST_MATERIAL                1658
#define BRSH_ED_NAME                    1662
#define BRSH_LB_INTERSECTIONS           1666
#define BRSH_BN_ADDINTERSECT            1670
#define BRSH_BN_DELETEINTERSECT         1674
#define BRSH_BN_OPTIMIZE                1678
#define BRSH_CK_HOLLOW                  1682
#define BRSH_ED_THICKNESS               1686
#define BRSH_CK_WAVY                    1690
#define BRSH_CK_DETAIL                  1694
#define BRSH_CK_AREA                    1698
#define BRSH_CK_FLOCKING                1702
#define BRSH_LB_CONTENTS                1706
#define GBAR_CB_GROUP                   1710
#define BRSH_BN_RESET                   1714
#define ENTY_ED_VALUE                   1718
#define BRSH_CB_TYPE                    1722
#define GRID_CB_ALWAYSSNAPVISIBLE       1726
#define GRID_RB_1                       1730
#define GRID_RB_2                       1734
#define TXTR_BN_128                     1738
#define GRID_RB_3                       1742
#define TXTR_BN_64                      1746
#define LTMP_ED_NAME                    1750
#define GRID_RB_4                       1754
#define TXTR_BN_32                      1758
#define LTMP_ED_RADIUS                  1762
#define GRID_RB_5                       1766
#define LTMP_ED_INTENSITY               1770
#define GRID_RB_6                       1774
#define DEFE_CB_ENTITIES                1778
#define DEFE_LB_PROPERTIES              1782
#define GRID_VIEW_VIEW1                 1786
#define DEFE_BN_NEW                     1790
#define GRID_VIEW_VIEW2                 1794
#define DEFE_BN_DELETE                  1798
#define GRID_VIEW_VIEW3                 1802
#define DEFE_BN_ADDFIELD                1806
#define GRID_VIEW_VIEW4                 1810
#define DEFE_BN_REMOVEFIELD             1814
#define DEFE_ED_FIELDNAME               1818
#define DEFE_                           1822
#define DEFE_CB_FIELDTYPE               1826
#define DEFE_ED_DEFSTRING               1830
#define DEFE_ED_DEFV1                   1834
#define DEFE_ED_DEFV2                   1838
#define DEFE_ED_DEFV3                   1842
#define DEFE_CB_DEFTF                   1846
#define DEFE_BN_COLOR                   1850
#define NMDL_ED_NAME                    1854
#define DEFE_BN_APPLY                   1858
#define ENTY_ED_DEFSTRING               1862
#define ENTY_ED_DEFV1                   1866
#define ENTY_ED_DEFV2                   1870
#define ENTY_ED_DEFV3                   1874
#define ENTY_CB_DEFTF                   1878
#define ENTY_BN_COLOR1                  1882
#define ENTY_BN_APPLY                   1886
#define IDC_HEIGHT                      1890
#define IDC_TERRAIN                     1894
#define IDC_STATIC_FILE                 1898
#define TERRIAN_MAP                     1906
#define LGHT_ED_RADIUS                  1910
#define LGHT_ED_BRIGHTNESS              1914
#define LGHT_ED_X                       1918
#define LGHT_ED_Y                       1922
#define LGHT_ED_Z                       1926
#define LGHT_BN_COLOR                   1930
#define LGHT_ED_NAME                    1934
#define LTMP_BN_COLOR                   1938
#define LGHT_ED_NUMBER                  1942
#define ENTY_ED_NAME                    1946
#define ENTY_ED_NUMBER                  1950
#define DEFE_ED_NAME                    1954
#define LIST_TV_ITEMS                   1958
#define SPHTMP_ED_RADIUS                1962
#define SPHTMP_ED_HBAND                 1966
#define SPHTMP_ED_VBAND                 1970
#define SPHTMP_ED_NAME                  1974
#define BOX_ED_BOTX                     1978
#define BOX_ED_BOTZ                     1982
#define BOX_ED_TOPX                     1986
#define BOX_ED_TOPZ                     1990
#define BOX_ED_Y                        1994
#define BOX_ED_NAME                     1998
#define CYLD_ED_TOPX                    2002
#define CYLD_ED_TOPZ                    2006
#define CYLD_ED_BOTX                    2010
#define CYLD_ED_BOTZ                    2014
#define CYLD_ED_STRIPES                 2018
#define CYLD_ED_NAME                    2022
#define IDC_GROUP                       2026
#define IDC_TYPE                        2030
#define IDC_ADDGROUP                    2034
#define IDC_GROUPRAIDO                  2038
#define IDC_TYPERADIO                   2042
#define IDC_MODELRAIDO                  2046
#define IDC_AREAS                       2050
#define IDC_VISPORTALS                  2054
#define IDC_SUBFACES                    2058
#define IDC_PORTALS                     2062
#define IDC_FACES                       2066
#define IDC_ADD                         2070
#define IDC_SPLITS                      2074
#define IDC_RESET                       2078
#define IDC_LEAFS                       2082
#define IDC_SUBTRACT                    2086
#define IDC_NODES                       2090
#define IDC_TOTALFACES                  2094
#define IDC_BRUSHES                     2098
#define IDC_VISFACES                    2102
#define IDC_CHECK1                      2106
#define IDC_VIEW_DISP_MOUSEPOS          2110
#define IDC_VIEW_SHOWMOUSEPOS           2114
#define IDC_CHECK2                      2118
#define IDC_VIEW_SHOWSIZE               2122
#define IDC_CHECK3                      2126
#define IDC_VIEW_RULER                  2130
#define IDC_SLIDER1                     2134
#define IDC_VIEW_CROSSCURSOR            2138
#define IDC_RADIO1                      2142
#define IDC_RADIO2                      2146
#define IDC_RADIO3                      2150
#define IDC_RADIO4                      2154
#define IDC_CANCEL                      2158
#define IDC_CSG                         2162
#define IDC_VIS                         2166
#define IDC_SOLID                       2170
#define IDC_BALANCE                     2174
#define IDC_LAZY                        2178
#define IDC_SMART                       2182
#define IDC_NORMAL                      2186
#define IDC_SUPER                       2190
#define IDC_RADIO_CUT                   2194
#define IDC_RADIO_EMPTY                 2198
#define IDC_RADIO_SOLID                 2202
#define IDC_LIGHTSONLY                  2206
#define IDC_LIGHT_ALL                   2210
#define IDC_REBUILDBSP                  2214
#define IDC_LIGHTS_DIRTY                2218
#define FACE_CK_MIRRO                   2222
#define FACE_CK_MIRROR                  2226
#define ALLMATERIALS_CB_GROUPNAME       2230
#define ALLMATERIALS_CB_MATERIALNAME    2234
#define ALLMATERIALS_PB_ADDMATERIAL     2238
#define ALLMATERIALS_PB_EDITMATERIAL    2242
#define ALLMATERIALS_LB_MATERIALS       2246
#define IDC_CK_LOCKTEXTURE              2250
#define IDC_MATERIALPREVIEW             2254
#define IDC_CONTENTS                    2258
#define IDC_BRUSH_ONUPDATE              2262
#define IDC_BRUSH_ONDESELECT            2266
#define IDC_BRUSH_ONCHANGE              2270
#define IDC_BRUSH_REALTIME              2274
#define IDC_BRUSH_LIGHTING              2278
#define IDC_LIGHT_ONUPDATE              2282
#define IDC_LIGHT_ONDESELECT            2286
#define IDC_LIGHT_ONCHANGE              2290
#define IDC_LIGHT_REALTIME              2294
#define IDC_UPDATEALL                   2298
#define IDC_UPDATE_SEL                  2302
#define IDC_EDIT1                       2306
#define IDC_TUTORIAL                    2310
#define IDC_PATH_TEXTURES               2314
#define IDC_EXTFILEDIALOG_TITLE_AUTHOR  2318
#define IDC_OBJECTTYPES                 2322
#define IDC_TUTORIAL2                   2326
#define IDC_EDIT2                       2330
#define IDC_GLOBAL_RECENTFILELIST       2334
#define IDC_ADDMODEL                    2338
#define IDC_DEMO                        2342
#define IDC_EDIT3                       2346
#define IDC_GLOBAL_NUMBACKUP            2350
#define IDC_TIMELINE_PLAY               2354
#define IDC_DEMO2                       2358
#define IDC_JET_FULLSCREEN              2362
#define IDC_TIMELINE_INSERT             2366
#define IDC_EDIT5                       2370
#define IDC_GLOBAL_INTERVALL            2374
#define IDC_TIMELINE_DELETE             2378
#define IDC_PATH_SHADERS                2382
#define IDC_TIMELINE_EVENTTEXT          2386
#define IDC_GLOBAL_UNDONUM              2390
#define IDC_TIMELINE_STOP               2394
#define IDC_PROP_TITLE                  2398
#define IDC_TIMELINE_INSERT_TIME        2402
#define IDC_TIMELINE_EDITKEY            2406
#define IDC_PROP_AUTHOR                 2410
#define IDC_TIMELINE_ZOOM_IN            2414
#define IDC_TIMELINE_ZOOM_OUT           2418
#define IDC_TIMELINE_ZOOM_IN2           2422
#define IDC_PROP_VERSION                2426
#define IDC_PROP_COMPANY                2430
#define IDC_ERROR                       2434
#define IDC_PROP_SUBJECT                2438
#define IDC_TIMELINE_MOD                2442
#define IDC_MORE                        2446
#define IDC_PROP_DESCRIPTION            2450
#define IDC_TIMELINE_CUTPOINT           2454
#define IDC_LOG                         2458
#define IDC_PROP_COMMENTS               2462
#define IDC_WARNINGICON                 2466
#define IDC_PROP_VALUE                  2470
#define IDC_TIMELINE_RESET              2474
#define IDC_TIMELINE_MOVEALL            2478
#define IDC_TIMELINE_MODE               2482
#define IDC_TIMELINE_CUT                2486
#define IDC_DEGREE_SNAP                 2490
#define IDC_TIMELINE_SMS                2494
#define IDC_SNAPVERTEXMANIP             2498
#define IDC_TIMELINE_HHMMSS             2502
#define IDC_MOUSE_MIDBUT                2506
#define IDC_HOTSELECT                   2510
#define IDC_STATIC_SHOW_COLOR1          2514
#define IDC_MOUSE_WHEEL                 2518
#define IDC_STATIC_SHOW_COLOR2          2522
#define IDC_STATIC_SHOW_COLOR3          2526
#define IDC_STATIC_DRIVER_TEXT          2530
#define IDC_STATIC_SHOW_COLOR4          2534
#define IDC_STATIC_SHOW_COLOR5          2538
#define IDC_STATIC_SHOW_COLOR6          2542
#define IDC_STATIC_SHOW_COLOR7          2546
#define IDC_STATIC_SHOW_COLOR8          2550
#define IDC_STATIC_SHOW_COLOR9          2554
#define IDC_STATIC_SHOW_COLOR10         2558
#define IDC_STATIC_SHOW_COLOR11         2562
#define IDC_STATIC_SHOW_COLOR12         2566
#define IDC_STATIC_PREVIEW              2570
#define IDC_STATIC_SHOW_COLOR13         2574
#define IDC_HOTSELECT1                  2578
#define IDC_PREFS_VIEW                  2582
#define IDC_PREFS_SNAP                  2586
#define IDC_PREFS_EDIT                  2590
#define IDC_PREFS_GLOBAL                2594
#define IDC_GRID_COLOR2                 2598
#define IDC_VIEW_SET_COLOR1             2602
#define IDC_STATIC_SNAPROTATE           2606
#define IDC_PREFS_KEYBOARD              2610
#define IDC_PREFS_PATHS                 2614
#define IDC_PATH_UBRUSH                 2618
#define IDC_STATIC_UBRUSH               2622
#define IDC_STATIC_TEXTURES             2626
#define IDC_PREFS_SCRIPT                2630
#define IDC_PREFS_JET                   2634
#define IDC_KEYS                        2638
#define IDC_PREFS_MOUSE                 2642
#define IDC_STATIC_RECT                 2646
#define IDC_STATIC_TEXTCOLOR            2650
#define IDC_ASSIGN                      2654
#define IDC_STATIC_MOUSETEXT1           2658
#define IDC_STATIC_MOUSETEXT2           2662
#define IDC_MOUSE_LEFTBUT               2666
#define IDC_MOUSE_WHEEL2                2670
#define IDC_STATIC_MOUSETEXT3           2674
#define IDC_MOUSE_RIGHTBUT              2678
#define IDC_STATIC_MOUSETEXT4           2682
#define IDC_STATIC_SHORTCUT             2686
#define IDC_PRESSKEY                    2690
#define IDC_CHECK_SHIFT                 2694
#define IDC_CHECK_ALT                   2698
#define IDC_CHECK_CONTROL               2702
#define IDC_EXPORTKEYS                  2706
#define IDC_IMPORTKEYS                  2710
#define IDC_VIEW_SET_COLOR2             2714
#define IDC_VIEW_SET_COLOR3             2718
#define IDC_VIEW_SET_COLOR4             2722
#define IDC_VIEW_SET_COLOR5             2726
#define IDC_VIEW_SET_COLOR6             2730
#define IDC_VIEW_SET_COLOR7             2734
#define IDC_VIEW_SET_COLOR8             2738
#define IDC_VIEW_SET_COLOR9             2742
#define IDC_VIEW_SET_COLOR10            2746
#define IDC_VIEW_SET_COLOR11            2750
#define IDC_VIEW_SET_COLOR12            2754
#define IDC_VIEW_SET_COLOR13            2758
#define IDC_SET_PATH_UBRUSH             2762
#define IDC_SET_PATH_TEXTURES           2766
#define IDC_STATIC_SHADERS              2770
#define GRID_VIEW_VIEWSNUM              2774
#define IDC_STATIC_SHORTCUT1            2778
#define IDC_STATIC_REBUILD_TEXT         2782
#define IDC_STATIC_SHORTCUT2            2786
#define IDC_STATIC_REBUILD_TEXT2        2790
#define IDC_KEYEDIT                     2794
#define IDC_STATIC_REBUILD_TEXT3        2798
#define IDC_PROPERTIES_CONTENTS         2802
#define IDC_STATIC_SHORTCUT3            2806
#define IDC_STATIC_REBUILD_TEXT4        2810
#define IDC_PROPERTIES_CUSTOM           2814
#define IDC_STATIC_VIEW_STATIC1         2818
#define IDC_PROP_ADD                    2822
#define IDC_UPDOWN                      2826
#define IDC_STATIC_TEXTCOLOR4           2830
#define IDC_PROP_VALUELIST              2834
#define IDC_EXTFILEDIALOG_TITLE         2838
#define IDC_STATIC_TEXTCOLOR5           2842
#define IDC_PROP_DEL                    2846
#define IDC_STATIC_LINE                 2850
#define IDC_STATIC_VIEW_STATIC2         2854
#define IDC_STATIC_PROP                 2858
#define IDC_STATIC_TEXTCOLOR7           2862
#define IDC_GLOBAL_STATIC2              2866
#define IDC_PROP_NAME                   2870
#define IDC_SHOW                        2874
#define IDC_STATIC_TEXTCOLOR2           2878
#define IDC_STATIC_TITLE                2882
#define IDC_STATIC_SNAP                 2886
#define IDC_TIME_MESSAGEID              2890
#define IDC_STATIC_TEXTCOLOR8           2894
#define IDC_GLOBAL_STATIC3              2898
#define IDC_TIME_OBJECTNAME             2902
#define IDC_STATIC_JET_TEXT1            2906
#define IDC_STATIC1                     2910
#define IDC_STATIC_JET_TEXT2            2914
#define IDC_STATIC2                     2918
#define IDC_CHOOSE_WINDOW               2922
#define IDC_STATIC3                     2926
#define IDC_CHOOSE_FULLSCREEN           2930
#define IDC_TIMELINE_CLR                2934
#define IDC_JET_WINDOW                  2938
#define IDC_STATIC_JET_TEXT3            2942
#define IDC_JET_COLL                    2946
#define IDC_JET_GRAV                    2950
#define IDC_JET_SLID                    2954
#define IDC_JET_STAIR                   2958
#define IDC_STATIC_TEXTCOLOR9           2962
#define IDC_GLOBAL_STATIC4              2966
#define IDC_JET_HEIGHT                  2970
#define IDC_STATIC_JET_TEXT4            2974
#define IDC_EDIT_KEY_INFO               2978
#define IDC_STATIC_TEXTCOLOR10          2982
#define IDC_GLOBAL_STATIC5              2986
#define IDC_STATIC_TEXTCOLOR11          2990
#define IDC_GLOBAL_STATIC6              2994
#define IDC_OK                          2998
#define IDC_GLOBAL_STATIC1              3002
#define IDC_STATIC_VIEW_STATIC3         3006
#define IDC_COMBO1                      3010
#define IDC_SET_PATH_SHADERS            3014
#define IDC_PROP_TYPE                   3018
#define IDC_CHECK4                      3022
#define IDC_GLOBAL_BACKUPONSAVE         3026
#define IDC_CHECK5                      3030
#define IDC_GLOBAL_INCREMENTONSAVE      3034
#define IDC_CHECK6                      3038
#define IDC_GLOBAL_SAVETHUMBERNAIL      3042
#define IDC_GLOBAL_SAVETHUMBNAIL        3046
#define IDC_GLOBAL_STATIC7              3050
#define IDC_SPIN1                       3054
#define IDC_GLOBAL_SPIN1                3058
#define IDC_CHECK7                      3062
#define IDC_GLOBAL_AUTOBACKUP           3066
#define IDC_SPIN2                       3070
#define IDC_GLOBAL_SPIN3                3074
#define IDC_SPIN3                       3078
#define IDC_GLOBAL_SPIN2                3082
#define IDC_GLOBAL_SPIN4                3086
#define IDC_GLOBAL_TOOLBAR_TEXT         3090
#define IDC_GLOBAL_TOOLBAR_FLAT         3094
#define IDC_GLOBAL_STATIC8              3098
#define IDC_GLOBAL_RELOAD               3102
#define IDC_PROP_STATIC1                3106
#define IDC_EDIT_STATIC                 3110
#define IDC_PROP_STATIC2                3114
#define IDC_EDIT_WINDOW                 3118
#define IDC_PROP_STATIC3                3122
#define IDC_DUMMY                       3126
#define IDC_PROP_STATIC4                3130
#define IDC_EDIT_STATIC2                3134
#define IDC_PROP_STATIC5                3138
#define IDC_EDIT_CROSSING               3142
#define IDC_PROP_STATIC6                3146
#define IDC_PROP_STATIC7                3150
#define IDC_PROP_STATIC8                3154
#define IDC_PROP_STATIC9                3158
#define IDC_PROP_STATIC10               3162
#define IDC_PROP_TRUE                   3166
#define IDC_PROP_FALSE                  3170
#define IDC_PROP_OK                     3174
#define IDS_MEMORY_ERR                  3178
#define IDS_DISPLAY_ERR                 3179
#define IDS_SOUND_ERR                   3180
#define IDS_SYSTEM_ERR                  3181
#define IDS_INTERNAL_ERR                3182
#define IDS_FILEOPEN_ERR                3183
#define IDS_FILECLOSE_ERR               3184
#define IDS_FILEREAD_ERR                3185
#define IDS_FILEWRITE_ERR               3186
#define IDS_FILEFORMAT_ERR              3187
#define IDS_FILEVERSION_ERR             3188
#define IDS_LISTFULL_ERR                3189
#define IDS_DATAFORMAT_ERR              3190
#define IDS_BADPARAMETER_ERR            3191
#define IDS_SEARCHFAILURE_ERR           3192
#define IDS_WINDOWS_ERR                 3193
#define IDS_SUBSYSTEM_ERR               3194
#define IDS_UNKNOWN_ERR                 3246
#define IDS_CONTEXT_OPEN                3250
#define IDS_CONTEXT_CLOSE               3254
#define IDR_FULLSCREEN                  3258
#define IDS_TOOLBAR_FULLSCREEN          3262
#define IDC_PROPERTIES_SUMMARY          3266
#define IDC_EXTFILEDIALOG_DESCRIPTION   3270
#define IDM_TOOLS_PLACECUBE             3274
#define IDM_TOOLS_PLACESPHEROID         3278
#define IDM_TOOLS_PLACECYLINDER         3282
#define IDM_TOOLS_PLACESTAIRCASE        3286
#define IDM_TOOLS_PLACEARCH             3290
#define IDM_TOOLS_PLACECONE             3294
#define IDM_TOOLS_PLACELIGHT            3298
#define ID_BUTTON32778                  3302
#define IDM_PLACESHEET                  3306
#define ID_BUTTON32779                  3310
#define IDR_IM_ACTOR                    3314
#define ID_BUTTON32781                  3318
#define ID_BUTTON32782                  3322
#define IDM_MODE_ADJUST                 3326
#define IDM_MODE_ROTATESHEAR            3330
#define IDM_MODE_VERTEX                 3334
#define IDM_VIEW_SHOWALLGROUPS          3338
#define IDM_VIEW_SHOWVISIBLEGROUPS      3342
#define IDM_VIEW_CURRENTGROUP           3346
#define IDM_EDIT_ADDTOGROUP             3350
#define IDM_EDIT_REMOVEFROMGROUP        3354
#define IDM_MODE_RELATIONS              3358
#define IDM_TOOLS_ADDBRUSH              3362
#define IDM_TOOLS_SUBTRACT              3366
#define IDM_TOOLS_SUBTRACTBRUSH         3370
#define IDM_TOOLS_REBUILDALL            3374
#define IDM_OPTIONS_SNAPTOGRID          3378
#define IDM_OPTIONS_GRID                3382
#define IDM_VIEW_ZOOMIN                 3386
#define IDM_VIEW_ZOOMOUT                3390
#define IDM_MODE_FACEMANIPULATION       3394
#define IDM_TOOLS_NEXTFACE              3398
#define IDM_TOOLS_PREVFACE              3402
#define IDM_TOOLS_DEFINEENTITIES        3406
#define IDM_TOOLS_PLACEENTITY           3410
#define IDM_TOOLS_BUILDLIGHTS           3414
#define ID_VIEW_PROPERTIES              3418
#define IDM_TOOLS_PLACECAMERA           3422
#define ID_VIEW_MODE                    3426
#define IDM_VIEW_CENTERSELCTION         3430
#define IDM_VIEW_ALLMATERIALS           3434
#define IDM_VIEW_LISTS                  3438
#define ID_BUTTON32818                  3442
#define ID_BUTTON32819                  3446
#define ID_BUTTON32820                  3450
#define ID_BUTTON32821                  3454
#define ID_BUTTON32822                  3458
#define IDM_TOOLS_PLACESPECIALEFFECT    3462
#define IDM_TOOLS_PLACESPECIALCURVE     3466
#define IDM_TOOLS_PLACEUSEROBJ          3470
#define IDM_TOOLS_PLACEACTOR            3474
#define IDM_TOOLS_PLACESHEET            3478
#define IDM_TOOLS_UPDATE_SELECTION      3482
#define IDM_TOOLS_PLACETERRAIN          3486
#define ID_MODE_ABORT                   3490
#define IDM_VIEW_OBJECTS                3494
#define IDM_FULLSCREEN_VIEW             3498
#define ID_3DVIEW_LINES                 3502
#define ID_3DVIEW_FLAT                  3506
#define ID_3DVIEW_BSPSPLITS             3510
#define ID_3DVIEW_TEXTURED              3514
#define ID_3DVIEW_TEXTUREDWLIGHTS       3518
#define ID_BUTTON32841                  3522
#define IDM_FULLSCREENHARDWARE_VIEW     3526
#define IDM_VIDEOSETTINGSWINDOW         3530
#define IDM_VIDEOSETTINGSFULLSCREEN     3534
#define IDM_VIDEOSETTINGS_FULLSCREENMODE 3538
#define IDM_VIDEOSETTINGS_WINDOWMODE    3542
#define IDM_ANIMATE                     3546
#define IDM_BILINEAR                    3550
#define IDS_UPDATE_ALL                  3554
#define ID_EDIT_CLONE                   3558
#define IDM_OPTIONS_MOUSEPROP           3562
#define IDM_EDIT_SELECTALL              3566
#define IDM_EDIT_SELECTNONE             3570
#define IDM_EDIT_SELECTINVERT           3574
#define IDM_EDIT_SELECTCAMERAS          3578
#define IDM_EDIT_SELECTBRUSHES          3582
#define IDM_EDIT_SELECTENTITIES         3586
#define IDM_EDIT_SELECTLIGHTS           3590
#define IDM_EDIT_SELECTMODELS           3594
#define IDM_EDIT_SELECTTERRAIN          3598
#define IDM_EDIT_SELECTUSER             3602
#define IDM_FILE_PREFS                  3606
#define IDM_POSSIZE_X                   3610
#define ID_FILE_EXPORT_SELECTEDOBJECTSASASCIIFILEJTA 3614
#define ID_FILE_IMPORT_JTAASCIIFIE      3618
#define IDM_POSSIZE_YSIZE               3622
#define IDM_POSSIZE_ZSIZE               3626
#define IDM_TOOLS_COMBOPLACEHOLDER      3630
#define IDM_POSSIZE_XSIZE               3634
#define ID_BUTTON32876                  3638
#define IDM_EDIT_ALIGN_LEFT             3642
#define IDM_EDIT_ALIGN_RIGHT            3646
#define IDM_EDIT_ALIGN_BOTTOM           3650
#define IDM_EDIT_ALIGN_TOP              3654
#define IDM_EDIT_GRID                   3658
#define IDM_EDIT_SNAP                   3662
#define ID_VIEW_EDIT                    3666
#define ID_VIEW_POSSIZE                 3670
#define IDM_VIEW_OBJECTSBAR             3674
#define IDM_ANIM                        3678
#define ID_TOOLBARS_CONFIGURE           3682
#define IDM_FULLSCREEN                  3686
#define ID_VIEW_TOOLBARS_FULLSCREEN     3690
#define ID_VIEW_FULLSCREEN              3694
#define IDM_FULLSCREEN_SHOW             3698
#define IDM_FULLSCREEN_PREVIEW          3702
#define ID_BUTTON32903                  3706
#define ID_BUTTON32905                  3710
#define ID_VIEW_TOOLBARS_CONFIGURE      3714
#define ID_FILE_FILEPROPERTIES          3718
#define IDM_EDIT_ROTR                   3722
#define IDM_EDIT_ROTL                   3726
#define IDM_EDIT_TOFRONT                3730
#define IDM_POSSIZE_Y                   3734
#define IDM_POSSIZE_Z                   3738
#define IDS_CMD_SELNONE                 3742
#define IDS_CMD_SELALL                  3746
#define IDS_CMD_ZOOMINOUT               3750
#define IDS_CMD_DISABLED                3754
#define IDB_BITMAP1                     4004
#define IDB_JET3D_SMALL                 4004
#define IDD_TEXTURES                    4005
#define IDR_POPUP_TEXTURE_TREELIST      4006
#define IDR_WORLDMODEL                  4007
#define IDD_DLG_AUTORECOVER             4008
#define IDR_LIGHT                       4009
#define IDD_OBJECTS                     4009
#define IDC_CURSOR1                     4012
#define IDC_ARCH                        4012
#define IDS_TAB_OBJECTS                 4014
#define ID_IDR_DELETEITEM               5001
#define ID_IDR_ADDGROUP                 5002
#define IDM_PROGRESS_CONTROL_CREATE     5003
#define IDM_PROGRESS_CONTROL_SETSTEP    5004
#define IDM_PROGRESS_CONTROL_STEP       5005
#define IDM_PROGRESS_CONTROL_DESTROY    5006
#define IDM_PROGRESS_CONTROL_SETRANGE   5007
#define ID_WORLDMODEL_CREATE            5008
#define ID_WORLDMODEL_EXPORTTOPREFAB    5009
#define ID_WORLDMODEL_IMPORTFROM        5010
#define IDM_EXPORT_PREFAB               5011
#define IDM_IMPORT_PREFAB               5012
#define ID_BUTTON5017                   5017
#define ID_BUTTON5019                   5019
#define ID_BUTTON5020                   5020
#define WM_JWEVIEW_AUTOSAVETIMER        5024
#define ID_AUTOSAVE_TIMER               5028
#define ID_FILE_EXPORT_EXPORTFORBTPROJECTWORKSPACEBTW 5032
#define ID_WORLDMODEL_SHOW              5034
#define ID_WORLDMODEL_INVERTSHOW        5035
#define ID_OBJECTCOMBO_SEPARATOR        5036
#define IDM_VIEW_SHOW_CURRENTGROUP      5037
#define IDM_VIEW_HIDE_CURRENTGROUP      5038
#define ID_MOVE_BACK                    5041
#define ID_MOVE_FORWARD                 5042
#define ID_MOVE_LEFT                    5043
#define ID_MOVE_RIGHT                   5044
#define IDC_CUSTOM2                     6013
#define IDC_ABOUT_TUTORIALS             6016
#define IDC_LIST_TEXTURES               6020
#define IDC_RADIO_TEX_32                6021
#define IDC_RADIO_TEX_64                6022
#define IDC_RADIO_TEX_128               6023
#define IDC_TREE_TEX_GROUPS             6025
#define IDC_TEX_PROPS                   6026
#define IDC_BUTTON_TEX_REFRESH          6027
#define IDC_STATIC_AUTORECOVER          6028
#define ID_AUTORECOVER_DELETE           6029
#define ID_AUTORECOVER_OPEN             6030
#define IDC_REFRESH                     6031
#define ID_VIEW_APPLOOK_WIN_2000        6032
#define ID_VIEW_APPLOOK_OFF_XP          6033
#define ID_VIEW_APPLOOK_WIN_XP          6034
#define ID_VIEW_APPLOOK_OFF_2003        6035
#define ID_VIEW_APPLOOK_VS_2005         6036
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   6037
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  6038
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 6039
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   6040

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        4015
#define _APS_NEXT_COMMAND_VALUE         5046
#define _APS_NEXT_CONTROL_VALUE         6041
#define _APS_NEXT_SYMED_VALUE           7001
#endif
#endif
